server:
  port: 82
  
spring:
  application:
    name: CFMS-provider-activiti
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/atcrowdfunding?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:84/eureka
